server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: master
        uri: lb://master
        predicates:
        - Path=/master/**
        filters:
        
